//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.13 at 11:48:51 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://demo.greatit.hu/guides/ws-country", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package hu.greatit.demo.guides.ws_country;
